[package]
name = "neat-rs"
version = "0.1.0"
authors = ["Shashi Kant <shashitnak@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.3"
slow_nn = "0.1.1"
gym = "2.2.1"